services:
  - type: web
    name: blackjack-multiplayer
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production